### ISSUE TITLE
consola does not work under AudioWorkletGlobalScope

### ISSUE THREAD

**Issue by baadc0de** [unjs/consola#83]
### Version

[v2.11.2](https://github.com/consola/releases/tag/v2.11.2)

### Reproduction link

[https://codesandbox.io/s/gracious-mendel-uw0vh](https://codesandbox.io/s/gracious-mendel-uw0vh)

### Steps to reproduce

Functions like setTimeout and clearTimeout are not defined on https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletGlobalScope

Logging with consola uses these functions in order to throttle logging. It should be possible to disable the throttling or have consola disable throttling if these functions are not available.

Creating a worklet.js file with the following code:
`console.log({setTimeout: typeof setTimeout, clearTimeout: typeof clearTimeout})`

And another file, index.js with the following:
`new AudioContext().audioWorklet.addModule("/worklet.js")`

Outputs
`{setTimeout: "undefined", clearTimeout: "undefined"}`

### What is expected ?

Consola to log without a crash

### What is actually happening?

Consola code crashes

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c62">#c62</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi and sorry for reply late. I think this issue is valid but the scope is limited. You might try to polyfill `globalThis.setTimeout` and `globalThis.clearTimeout` to make it working. When using Nuxt 3 or Nitro / Unenv, does the polyfill too.

Closing issue since is stalled. Please let me know if you still thinks worth to implement polyfill built-in.
